"""empty message

Revision ID: 9eb3def5daf4
Revises: 
Create Date: 2020-08-25 18:47:04.353217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb3def5daf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pickup_name', sa.String(), nullable=True),
    sa.Column('pickup_address', sa.String(), nullable=True),
    sa.Column('pickup_number', sa.String(length=10), nullable=True),
    sa.Column('dropoff_name', sa.String(), nullable=True),
    sa.Column('dropoff_address', sa.String(), nullable=True),
    sa.Column('dropoff_number', sa.String(length=10), nullable=True),
    sa.Column('manifest', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
